POST https://node-fullstack-8qo3.onrender.com/videos
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Essse é o numero um do video YOUTUBE",
    "duration": 180
    
}

###

GET  https://node-fullstack-8qo3.onrender.com/videos?search=

###
PUT https://node-fullstack-8qo3.onrender.com/videos/{id}
Content-Type: application/json

{
    "title": "Video 01 Atualizado",
    "description": "Teste Tavares",
    "duration": 200
}
###

DELETE http://localhost:3333/videos/b99cbffa-df8c-4f37-af98-7ab55756c10d
